### ISSUE TITLE
Como usuario, necesito un login para que no me olviden

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#1]

**Comment by Marius115** [comment]
![Image](https://user-images.githubusercontent.com/96928602/180656940-e61139ee-7703-45ef-bef8-d001d8ee89dc.png)

**Comment by Marius115** [comment]
DIseño de login aspectos tecnicos:
"Login de usuario" : h1
email : 
-<input> 
-placeholder type: text ( round borders, font color: light grey)

password:
-placeholder type: password ( round borders, font color: light grey)

2do div: opacity 60-80%

**Comment by Marius115** [comment]
falta estilizar para completar esta tarea

**Comment by Marius115** [comment]
Wilfredo estilizo el Login
