### ISSUE TITLE
Crear modelo de datos de caimaneras #5

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#10]

**Comment by Marius115** [comment]
class Caimanera(db.Model):
	id =db.Column(db.Integer, primary_key= True)
	name =db.Column(db.String(120), unique = True, nullable= False)	
	date =db.Column(db.String(120), unique = True, nullable= False)
	time =db.Column(db.String(120), unique = True, nullable= False)
	location = db.Column(db.String(120), unique = True, nullable = False)
	creator = db.Column(db.Integer, db.ForeignKey("user,id"))

	def __init__(self, date,time,location,creator):
			self.date = date
			self.time = time   
			self.name = name  
			self.location = location
			self.creator = creator
      db.session.add(self)
      db.session.commit()

	def serialize(self):
      return {
						"id":self.id,
						"name":self.name,
						"time":self.time,
		        "date":self.date,
						"location":self.location,
						"creator":self.creator}

**Comment by Marius115** [comment]
se simplifico el modelo de base de datos  al usar la propiedad datetime en lugar de usar 2 propiedades por separado

**Comment by Marius115** [comment]
Nuevo modelo de caimaneras:


class Caimanera(db.Model):
	id =db.Column(db.Integer, primary_key= True)
	datetime =db.Column(db.String(120), unique = True, nullable= False)
	location = db.Column(db.String(120), unique = True, nullable = False)
	creator = db.Column(db.Integer, db.ForeignKey("user.id"))

	def __init__(self, datetime,location,creator):
			self.datetime = datetime     
			self.location = location
			self.creator = creator
                         db.session.add(self)
                         db.session.commit()

	def serialize(self):
         return {
						"id":self.id,
		        "datetime":self.datetime,
						"location":self.location,
						"creator":self.creator}

**Comment by Marius115** [comment]
falta agregar name

**Comment by Marius115** [comment]
agregado propiedad name
