### ISSUE TITLE
crear modelo de datos de inscripciones # 5

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#11]

**Comment by Marius115** [comment]
`class Inscription(db.Model):
	id = db.Column(db.Integer, primary_key= True)
	event = db.Column(db.Integer, db.ForeignKey("caimanera.id")	
	players = db.Column(db.Integer, db.ForeignKey("user.id")		


def __init__(self, event, players,):
			self.event = event
			self.players = players
                        db.session.add(self)
                        db.session.commit()


	def serialize(self):
      return {
			"id":self.id,
		        "event":self.event
			"players":self.player}
