### ISSUE TITLE
crear modelo usuario # 3

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#12]

**Comment by Marius115** [comment]
Posible modelo de usuario:

class User(db.Model):
        id = db.Column(db.Integer, primary_key= True)
	email = db.Column(db.String(120), unique = True, nullable= false)
	password = db.Column(db.String(80), unique = False, nullable= False)
	is_active = db.Column(db.Boolean(), unique=False, nullable=False)

**Comment by wiljmorales** [comment]
Hace falta agredar nombre del usuario

**Comment by Marius115** [comment]
Se agrega el nombre del usuario al modelo

**Comment by Marius115** [comment]
Se agrega el nombre del usuario al modelo
