### ISSUE TITLE
Como usuario quiero organizar una caimanera

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#5]

**Comment by wiljmorales** [comment]
- [ ] introducir fecha, hora y lugar
- [ ] introducir cantidad de equipos

**Comment by wiljmorales** [comment]
metodo POST  a  /api/caimaneras
request body {
  "fecha": "datetime",
  "hora": "10 pm",
  "lugar": "la urba"
}
response body {
  "id": 1
  "organizado_id"
  "fecha": "datetime",
  "hora": "10 pm",
  "lugar": "la urba"
  "inscritos": [{
  "id":
  "id_caimanera":
  "id_jugador":
}]
}

**Comment by Marius115** [comment]
![Image](https://user-images.githubusercontent.com/96928602/180657242-067c4189-a242-4676-8a24-6e80954d065d.png)

**Comment by Marius115** [comment]
Idea para la vista de registro:
-se puede eliminar el jumbotron
-nose del navbar
-se puede cambiar el fondo.
-mejor color del texto constante
-ideas dentro del espacio de input

**Comment by Marius115** [comment]
Data modelling de La canchita

![Screenshot_2022-07-25-21-03-36-925_com.drawexpress.lite.jpg](https://user-images.githubusercontent.com/96928602/180912413-732928cb-9b26-4475-9075-80375f9694a4.jpg)

**Comment by Marius115** [comment]
> Data modelling de La canchita
> 
> ![Screenshot_2022-07-25-21-03-36-925_com.drawexpress.lite.jpg](https://user-images.githubusercontent.com/96928602/180912413-732928cb-9b26-4475-9075-80375f9694a4.jpg)

Un user solo puede llegar a las caimaneras ya sea uniendose o creandola, un usuario puede crear y unirse a muchas caimaneras (relacion muchos a muchos), pero la creacion o inscripcion solo puede ser para una caimanera por vez (uno a uno)

**Comment by Marius115** [comment]
![Screenshot_2022-07-26-03-35-03-894_com.drawexpress.lite.jpg](https://user-images.githubusercontent.com/96928602/180953496-df3e7f01-2734-491b-a259-825146b9b2ff.jpg)

 2da idea:
- relacion de usuario/caimaneras es muchos a muchos
- relacion usuario/inscripcion es muchos a muchos.
- relacion caimaneras/inscripcion es 1 a 1

**Comment by Marius115** [comment]
Solo falta metodo post para este task

**Comment by Marius115** [comment]
listo el metodo post
