### ISSUE TITLE
Crear metodo post de /caimaneras #5

### ISSUE THREAD

**Issue by wiljmorales** [wiljmorales/la-canchita#9]

**Comment by Marius115** [comment]
Idea de metodo post de /Caimanera:

`@api.route('/caimanera', method = ['POST'])
def create_caimanera():
	body = request.json
	name = body.get('name', None)
	date = body.get('date', None)
	time = body.get('time', None)
	location = body.get('location',None)
	if date is None or time is None or location is None or name is None: return jsonify(
	"param missing in payload"),400
	new_caimanera =Caimanera(name,date,time,location)
	return (new_caimanera.serialize()),201
	`

**Comment by Marius115** [comment]
Cambiado y mejorado el metodo post:

- incluye el jwt token
- relaciona el user con la caimanera
- falta agregar name asi como en el modelo de caimanera

**Comment by Marius115** [comment]
agregado name en el body request de routes.py
